project-id: my-test-project-168110
duration: 22m
groups:
  - name: mongo-cluster
    zone: us-central1-c
    instances: [instance-1, mongo-2]
    failure:
      interval: 10s
      probability: 0.5
      strategy: Reset